{
 "title": "webservice",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "SLO", "query": "0.001,0.01,0.02,0.05,0.1" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate - 1h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webservice:error_rate:5m", "legendFormat": "5m" },
    { "expr": "webservice:error_rate:1h", "legendFormat": "1h" },
    {
     "expr": "(webservice:error_rate:5m > 14.4*$SLO)\nand\n(webservice:error_rate:1h > 14.4*$SLO)",
     "legendFormat": "Alert"
    },
    { "expr": "14.4*$SLO", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Succes Rate - 1h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[5s])) / sum(rate(webservice_http_request_duration_seconds_count{}[5s]))",
     "legendFormat": "5m"
    },
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[1m])) / sum(rate(webservice_http_request_duration_seconds_count{}[1m]))",
     "legendFormat": "1h"
    },
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[5s])) / sum(rate(webservice_http_request_duration_seconds_count{}[5s])) < (1-14.4*$SLO)\nand\nsum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[1m])) / sum(rate(webservice_http_request_duration_seconds_count{}[1m])) < (1-14.4*$SLO)",
     "legendFormat": "Alert"
    },
    { "expr": "(1-14.4*$SLO)", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Error Rate - 6h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webservice:error_rate:30m", "legendFormat": "30m" },
    { "expr": "webservice:error_rate:6h", "legendFormat": "6h" },
    {
     "expr": "(webservice:error_rate:30m > 6*$SLO)\nand\n(webservice:error_rate:6h > 6*$SLO)",
     "legendFormat": "Alert"
    },
    { "expr": "6*$SLO", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Succes Rate - 6h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[30s])) / sum(rate(webservice_http_request_duration_seconds_count{}[30s]))",
     "legendFormat": "30m"
    },
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[6m])) / sum(rate(webservice_http_request_duration_seconds_count{}[6m]))",
     "legendFormat": "6h"
    },
    {
     "expr": "(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[30s])) / sum(rate(webservice_http_request_duration_seconds_count{}[30s])) < (1-6*$SLO))\nand\n(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[6m])) / sum(rate(webservice_http_request_duration_seconds_count{}[6m])) < (1-6*$SLO))",
     "legendFormat": "Alert"
    },
    { "expr": "1-(6*$SLO)", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Error Rate - 24h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webservice:error_rate:2h", "legendFormat": "2h" },
    { "expr": "webservice:error_rate:24h", "legendFormat": "24h" },
    {
     "expr": "(webservice:error_rate:2h > 3*$SLO)\nand\n(webservice:error_rate:24h > 3*$SLO)",
     "legendFormat": "Alert"
    },
    { "expr": "3*$SLO", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Succes Rate - 24h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[2m])) / sum(rate(webservice_http_request_duration_seconds_count{}[2m]))",
     "legendFormat": "2h"
    },
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[24m])) / sum(rate(webservice_http_request_duration_seconds_count{}[24m]))",
     "legendFormat": "24h"
    },
    {
     "expr": "(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[2m])) / sum(rate(webservice_http_request_duration_seconds_count{}[2m])) < (1-3*$SLO))\nand\n(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[24m])) / sum(rate(webservice_http_request_duration_seconds_count{}[24m])) < (1-3*$SLO))",
     "legendFormat": "Alert"
    },
    { "expr": "1-(3*$SLO)", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Error Rate - 72h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webservice:error_rate:6h", "legendFormat": "6h" },
    { "expr": "webservice:error_rate:72h", "legendFormat": "72h" },
    {
     "expr": "(webservice:error_rate:6h > 1*$SLO)\nand\n(webservice:error_rate:72h > 1*$SLO)",
     "legendFormat": "Alert"
    },
    { "expr": "1*$SLO", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Succes Rate - 72h Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[6m])) / sum(rate(webservice_http_request_duration_seconds_count{}[6m]))",
     "legendFormat": "6h"
    },
    {
     "expr": "sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[72m])) / sum(rate(webservice_http_request_duration_seconds_count{}[72m]))",
     "legendFormat": "72h"
    },
    {
     "expr": "(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[6m])) / sum(rate(webservice_http_request_duration_seconds_count{}[6m])) < (1-1*$SLO))\nand\n(sum(rate(webservice_http_request_duration_seconds_count{code!~\"5.*\"}[72m])) / sum(rate(webservice_http_request_duration_seconds_count{}[72m])) < (1-1*$SLO))",
     "legendFormat": "Alert"
    },
    { "expr": "1-(1*$SLO)", "legendFormat": "Threshold" }
   ]
  }
 ]
}