global:
  scrape_interval: 1s

scrape_configs:
- job_name: webservice
  static_configs:
  - targets:
    - webservice:5555

rule_files:
  - "/etc/prometheus/rules/one.yaml"
#   - /etc/prometheus/rules/*.yml
