# Default values for webservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: a07ad5e7.ngrok.io/jimmyjames85/webservice
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer

# NOTE: actual resource usage will be doubled since there are two
# containters
resources:
  limits:
   cpu: 1
   memory: 1Gi
  requests:
   cpu: 1
   memory: 1Gi

env:
  WEBSERVICE_PORT: 5555
